### ISSUE TITLE
cjs/ejs files not included in the module

### ISSUE THREAD

**Issue by adamkiss** [ederssouza/vanillajs-scrollspy#17]
In the `package.json`, you're defining main/module paths for ejs/cjs files, but there's only the iife file in the dist folder and indeed, delivered when installing with npm.

**Comment by ederssouza** [comment]
The bug was fixed in the 3.0.8 version.
<img width="235" alt="Screenshot 2023-10-13 at 11 14 26" src="https://github.com/ederssouza/vanillajs-scrollspy/assets/3737645/3b81f438-09ae-46fd-9e2d-826599676edc">
