### ISSUE TITLE
Offset top?

### ISSUE THREAD

**Issue by tmblog** [ederssouza/vanillajs-scrollspy#3]
Hi thank you for the excellent plugin, I have a small issue where the active div becomes active half way into the page e.g. as soon as its in view. Is there a way to offset from the top so that it scrolls to say around 15px from top? Ideally like when it hits the `#scrollNav`.
Cheers
Here's my mark up:

```
<style>
	div.scrollmenu {
	  background-color: #333;
	  overflow: auto;
	  white-space: nowrap;
	}
	div.scrollmenu a {
	  display: inline-block;
	  color: white;
	  text-align: center;
	  padding: 14px;
	  text-decoration: none;
	}

	div.scrollmenu a:hover {
	  background-color: #777;
	}

	div.scrollmenu a.active {
	  background-color: red;
	}
</style>
<div class="sticky-top scrollmenu" id="scrollNav">
	<a href="#About">About</a>
	<a href="#Blogs">Blogs</a>
	<a href="#Contact">Contact</a>
	<a href="#Map">Map</a>
</div>

<div id="About">	
	<div class="card mt-1 list-group-item list-group-item-action p-0">
		<div class="card-body row">
			<div class="col">
				<p class="lead mb-1">About</p>
                                        Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.
			</div>
		</div>
	</div>
</div>

<div id="Blogs">
...
```

**Comment by ederssouza** [comment]
Hello @tmblog. About the offset calculation. The calc seems correct. With my experience in building, the plugin I recommend you use "padding" in the section blocks (#About, #Blogs, #Contact, #Map). "magin" attribute does not work, and calculation is imprecise. Check also your CSS reset. Try these tips and return ok?
